### ISSUE TITLE
Update reading from `~/.config/maestro` to `~/.maestro`

### ISSUE THREAD

**Issue by T-monius** [maestro-framework/maestro#48]
Determine where AWS account information is being read and make the update.

**Comment by zklamm** [comment]
I believe I jumped the gun and already made this change as part of PR #52. See [here](https://github.com/maestro-framework/maestro/pull/52/commits/30c9c74b6cf4897efd47ab372be2553dd297530e) Please let me know if the code change that I linked does not fully address this GitHub issue. If it does, then I think we can close this issue. Otherwise, we should update this issue to list the remaining work.

**Comment by T-monius** [comment]
The reading change made in PR #52 was updated in PR #54 , so thanks to your efforts and the new PR, this issue can be closed when #54 pulled in.
